<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="46" started-at="2013-12-23T10:50:52Z" finished-at="2013-12-23T10:50:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="46" started-at="2013-12-23T10:50:52Z" finished-at="2013-12-23T10:50:52Z">
      <class name="test.test.pagesTest">
        <test-method status="PASS" signature="testRegistration()[pri:0, instance:test.test.pagesTest@7eceb95b]" name="testRegistration" duration-ms="15" started-at="2013-12-23T12:50:52Z" finished-at="2013-12-23T12:50:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRegistration -->
        <test-method status="PASS" signature="testSomeFails()[pri:0, instance:test.test.pagesTest@7eceb95b]" name="testSomeFails" duration-ms="10" started-at="2013-12-23T12:50:52Z" finished-at="2013-12-23T12:50:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSomeFails -->
        <test-method status="PASS" signature="testSomeFails2()[pri:0, instance:test.test.pagesTest@7eceb95b]" name="testSomeFails2" duration-ms="1" started-at="2013-12-23T12:50:52Z" finished-at="2013-12-23T12:50:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSomeFails2 -->
        <test-method status="FAIL" signature="testSomeFails3()[pri:0, instance:test.test.pagesTest@7eceb95b]" name="testSomeFails3" duration-ms="1" started-at="2013-12-23T12:50:52Z" finished-at="2013-12-23T12:50:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Values are not equal expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Values are not equal expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at test.test.pagesTest.testSomeFails3(pagesTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSomeFails3 -->
        <test-method status="PASS" signature="testSomeFails4()[pri:0, instance:test.test.pagesTest@7eceb95b]" name="testSomeFails4" duration-ms="0" started-at="2013-12-23T12:50:52Z" finished-at="2013-12-23T12:50:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSomeFails4 -->
      </class> <!-- test.test.pagesTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
